export {default as HomeLayOut} from "./HomLayOut"
export {default as Inbox} from "./Inbox"
export {default as SentBox} from "./SentBox"
export {default as Favourite} from "./Favourite"
export {default as Login} from "./Login"
export {default as Register} from "./Register"
export {default as SideBar} from "./SideBar"
export {default as NavLinks} from "./NavLinks"
export {default as EmailDetails} from "./EmailDetails"

